# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnceKitDemo' do
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'OnceKit'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OnceKitDemo

  target 'OnceKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnceKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
